---

# Конфигурация панели Flow, построенная в формате из официального репозитория.
# Якоря ниже позволяют переиспользовать одинаковые наборы порогов для всех узлов.
anchorThresholds:
  - thresholds: &util_percent
      - {color: "semi-dark-green", level: 0}
      - {color: "orange", level: 70}
      - {color: "red", level: 90}

cellIdPreamble: ""
gradientMode: "hue"

cells:
  # --- PVE cluster узлы ---
  pve0_cpu:
    dataRef: "pve0_cpu"
    label:
      separator: "colon"
      units: "percent(0-100)"
      decimalPoints: 1
    labelColor:
      thresholds: *util_percent
  pve0_mem:
    dataRef: "pve0_mem"
    label:
      separator: "colon"
      units: "percent(0-100)"
      decimalPoints: 1
    labelColor:
      thresholds: *util_percent
  4imd3VvK-_OE2TMO21Rd-4:
    dataRef: "pve0_zfs_total"
    label:
      separator: "colon"
      units: "none"
      unitsPostfix: " GiB"
      decimalPoints: 1
  4imd3VvK-_OE2TMO21Rd-5:
    dataRef: "pve0_zfs_free"
    label:
      separator: "colon"
      units: "none"
      unitsPostfix: " GiB"
      decimalPoints: 1

  4imd3VvK-_OE2TMO21Rd-7:
    dataRef: "pve1_cpu"
    label:
      separator: "colon"
      units: "percent(0-100)"
      decimalPoints: 1
    labelColor:
      thresholds: *util_percent
  4imd3VvK-_OE2TMO21Rd-8:
    dataRef: "pve1_mem"
    label:
      separator: "colon"
      units: "percent(0-100)"
      decimalPoints: 1
    labelColor:
      thresholds: *util_percent
  4imd3VvK-_OE2TMO21Rd-9:
    dataRef: "pve1_zfs_total"
    label:
      separator: "colon"
      units: "none"
      unitsPostfix: " GiB"
      decimalPoints: 1
  4imd3VvK-_OE2TMO21Rd-10:
    dataRef: "pve1_zfs_free"
    label:
      separator: "colon"
      units: "none"
      unitsPostfix: " GiB"
      decimalPoints: 1

  4imd3VvK-_OE2TMO21Rd-12:
    dataRef: "pve2_cpu"
    label:
      separator: "colon"
      units: "percent(0-100)"
      decimalPoints: 1
    labelColor:
      thresholds: *util_percent
  4imd3VvK-_OE2TMO21Rd-13:
    dataRef: "pve2_mem"
    label:
      separator: "colon"
      units: "percent(0-100)"
      decimalPoints: 1
    labelColor:
      thresholds: *util_percent
  4imd3VvK-_OE2TMO21Rd-14:
    dataRef: "pve2_zfs_total"
    label:
      separator: "colon"
      units: "none"
      unitsPostfix: " GiB"
      decimalPoints: 1
  4imd3VvK-_OE2TMO21Rd-15:
    dataRef: "pve2_zfs_free"
    label:
      separator: "colon"
      units: "none"
      unitsPostfix: " GiB"
      decimalPoints: 1

  # --- Виртуальные машины ---
  4imd3VvK-_OE2TMO21Rd-17:
    dataRef: "ms_mn_c1_cpu"
    label:
      separator: "colon"
      units: "percent(0-100)"
      decimalPoints: 1
    labelColor:
      thresholds: *util_percent
  4imd3VvK-_OE2TMO21Rd-18:
    dataRef: "ms_mn_c1_mem"
    label:
      separator: "colon"
      units: "percent(0-100)"
      decimalPoints: 1
    labelColor:
      thresholds: *util_percent
  4imd3VvK-_OE2TMO21Rd-19:
    dataRef: "ms_mn_c1_storage_total"
    label:
      separator: "colon"
      units: "none"
      unitsPostfix: " GiB"
      decimalPoints: 1
  4imd3VvK-_OE2TMO21Rd-25:
    dataRef: "ms_mn_c1_storage_free"
    label:
      separator: "colon"
      units: "none"
      unitsPostfix: " GiB"
      decimalPoints: 1

  4imd3VvK-_OE2TMO21Rd-28:
    dataRef: "c3_cpu"
    label:
      separator: "colon"
      units: "percent(0-100)"
      decimalPoints: 1
    labelColor:
      thresholds: *util_percent
  4imd3VvK-_OE2TMO21Rd-29:
    dataRef: "c3_mem"
    label:
      separator: "colon"
      units: "percent(0-100)"
      decimalPoints: 1
    labelColor:
      thresholds: *util_percent
  4imd3VvK-_OE2TMO21Rd-30:
    dataRef: "c3_storage_total"
    label:
      separator: "colon"
      units: "none"
      unitsPostfix: " GiB"
      decimalPoints: 1
  4imd3VvK-_OE2TMO21Rd-31:
    dataRef: "c3_storage_free"
    label:
      separator: "colon"
      units: "none"
      unitsPostfix: " GiB"
      decimalPoints: 1

  4imd3VvK-_OE2TMO21Rd-33:
    dataRef: "taxcom_cpu"
    label:
      separator: "colon"
      units: "percent(0-100)"
      decimalPoints: 1
    labelColor:
      thresholds: *util_percent
  4imd3VvK-_OE2TMO21Rd-34:
    dataRef: "taxcom_mem"
    label:
      separator: "colon"
      units: "percent(0-100)"
      decimalPoints: 1
    labelColor:
      thresholds: *util_percent
  4imd3VvK-_OE2TMO21Rd-35:
    dataRef: "taxcom_storage_total"
    label:
      separator: "colon"
      units: "none"
      unitsPostfix: " GiB"
      decimalPoints: 1
  4imd3VvK-_OE2TMO21Rd-36:
    dataRef: "taxcom_storage_free"
    label:
      separator: "colon"
      units: "none"
      unitsPostfix: " GiB"
      decimalPoints: 1

  # --- Veeam ---
  veeam_status:
    dataRef: "veeam_status"
    label:
      separator: "colon"
      units: "string"
